// MIT License
//
// Copyright (c) 2018 Emmanuel Arias
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
package codegen

import (
	"io"
	"text/template"

	"github.com/eariassoto/scxml_fsm_generator/internal/tomlparser"
)

const fsmCodeTemplateFile = `{{- $FSMName := .Name -}}
// Code generated by go generate; DO NOT EDIT
// This file was generated by robots at {{ .Timestamp }}
package {{.Package}}

type {{$FSMName}}State int

type {{$FSMName}}Stimulus int

const (
{{- range $index, $element := .States}}
	{{.Name}} {{$FSMName}}State = {{$index}}
{{- end}}
)

const (
{{- range $index, $element := .Transitions}}
	{{.Event}} {{$FSMName}}Stimulus = {{$index}}
{{- end}}
)

type {{$FSMName}}StateMachine struct {
	CurrentState {{$FSMName}}State
	Data         interface{}
}
type fsmError struct {
	s string
}
func (e *fsmError) Error() string {
	return e.s
}
func New{{$FSMName}}StateMachine(data interface{}) *{{$FSMName}}StateMachine {
	return &{{$FSMName}}StateMachine{ {{- .InitialState}}, data}
}

func Get{{$FSMName}}StimulusString(stimulus {{$FSMName}}Stimulus) string {
	switch stimulus {
{{- range $element := .Transitions}}
	case {{.Event}}:
		return "{{.Event}}"
{{- end}}
	default:
		return ""
	}
}

func Get{{$FSMName}}StateString(state {{$FSMName}}State) string {
	switch state {
{{- range .States}}
	case {{.Name}}:
		return "{{.Name}}"
{{- end}}
	default:
		return ""
	}
}

func (fsm *{{$FSMName}}StateMachine) MoveNextState(stimulus {{$FSMName}}Stimulus) ({{$FSMName}}State, error) {
	nextState, err := fsm.GetNextState(stimulus)
	if err != nil {
		return fsm.CurrentState, err
	}
	cbs := GetOnExitCallback(fsm.CurrentState)
	for _, cb := range cbs {
		cb(fsm.Data)
	}
	if fsm.CurrentState == nextState {
		cbs = GetOnLoopCallback(fsm.CurrentState)
		for _, cb := range cbs {
			cb(fsm.Data)
		}
	} else {
		cbs = GetOnEntryCallback(nextState)
		for _, cb := range cbs {
			cb(fsm.Data)
		}
	}
	fsm.CurrentState = nextState
	return nextState, nil
}

`

// GenerateCodeForFSM takes a parsed SCXML file and generated the code
// from a pre-defined template. All of the code for a FSM will be written
// in a single Writer.
func GenerateCodeForFSM(fsm *tomlparser.TomlFSM, outputFile io.Writer) error {
	fsmTemplate := template.Must(template.New(fsm.Name).Parse(fsmCodeTemplateFile))
	return fsmTemplate.Execute(outputFile, fsm)
}
